version: '2'

services:
  plex:
    # https://hub.docker.com/r/lsioarmhf/plex/
    image: lsioarmhf/plex:latest
    container_name: plex
    restart: always
    environment:
      - PLEX_CLAIM="${PLEX_TOKEN}"
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    network_mode: "host"
    ports:
      - "32400:32400"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media/movies:/data/movies
      - /mnt/media/series:/data/tvshows
      - /mnt/docker/plex/config/:/config
      - /mnt/media/plex_transcode/:/transcode

  transmission:
    # https://hub.docker.com/r/lsioarmhf/transmission/
    image: lsioarmhf/transmission:latest
    container_name: transmission
    restart: always
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    ports:
      - "9091:9091"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/transmission/config/:/config
      - /mnt/media/downloads/:/downloads

  sonarr:
    # https://hub.docker.com/r/lsioarmhf/sonarr/
    image: lsioarmhf/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - /mnt/media/series:/tv
      - /mnt/docker/sonarr/config:/config
      - /mnt/media/downloads/:/downloads

  radarr:
    # https://hub.docker.com/r/lsioarmhf/radarr/
    image: lsioarmhf/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - /mnt/media/movies:/movies
      - /mnt/docker/radarr/config:/config
      - /mnt/media/downloads/:/downloads

  # Proxy to a bunch of public trackers
  jackett:
    # https://hub.docker.com/r/lsioarmhf/jackett/
    image: lsioarmhf/jackett:latest
    container_name: jackett
    restart: always
    dns: 8.8.8.8
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    ports:
      - "9117:9117"
    volumes:
      - /mnt/docker/jackett/config/:/config
      - /mnt/media/downloads/:/downloads

  nextcloud:
    image: arm32v7/nextcloud:latest
    container_name: nextcloud
    restart: always
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /mnt/media/cloud:/var/www/html/data
      - /mnt/docker/nextcloud:/var/www/html/config

  https-portal:
    image: ejsfreitas/https-portal:armv7-1.0.0
    container_name: https-portal
    restart: always
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'cloud.${DOMAIN_NAME} -> http://nextcloud:80'
      STAGE: 'production'
      FORCE_RENEW: 'true'
      CLIENT_MAX_BODY_SIZE: 0
